version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: middle_postgres
    environment:
      POSTGRES_DB: middle_order
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    container_name: middle_postgres_test
    environment:
      POSTGRES_DB: middle_order_test
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: middle_redis
    ports:
      - "6379:6379"

volumes:
  pg_data: